org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
gtm_version=7.1.4
gtm_version_range=[1.6,)
ae2_version=15.4.10
ae2_version_range=[15,)
jei_version=15.20.0.112
emi_version=1.1.22+1.20.1
registrate_version=MC1.20-1.3.3
ldlib_version=1.0.31
adae_version=6757852
geckolib_version=6789487
exae_version=6870350
glodium_version=5226922
appflux_version=6755986
mae2_version=6827727
jade_version=6855440
guideme_version=20.1.11
guideme_version_range=[20.1.3,)
expanded_ae_version=7043985
expanded_ae_version_range=[1.2.5,)
mega_cells_version=6175008
cloth_config_version=11.1.136
wireless_terminals_version=5217955
curios_version=5.14.1+1.20.1
architectury_version=5137938

mod_id=pccard
mod_name=Programmed Circuit Card
mod_license=MIT
mod_version=1.2.3
mod_group_id=yuuki1293.pccard
mod_authors=yuuki1293
mod_description=Add a Programmed Circuit Card
version_type=release
