org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.193
loader_version_range=[1,)

gtm_version=7.0.1
gtm_version_range=[7.0,)
registrate_version=MC1.21-1.3.0+67
configuration_version=v3.1.1
ae2_version=19.2.13
ae2_version_range=[19.0.2,)
jei_version=19.22.0.315
emi_version=1.1.22+1.21.1
ldlib_version=1.0.35.a
adae_version=6225993
geckolib_version=6659026
exae_version=6786438
glodium_version=5821676
appflux_version=6649565
jade_version=6738687
guideme_version=21.1.13
guideme_version_range=[21,)
expanded_ae_version=6764610
mega_cells_version=6633684

mod_id=pccard
mod_name=Programmed Circuit Card
mod_license=MIT
mod_version=1.0.0
mod_group_id=yuuki1293.pccard
mod_authors=yuuki1293
mod_description=Add a Programmed Circuit Card
version_type=release
